apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simple-jwt-api
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

  - name: ng-2
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
